- DEVICE_IP: 192.168.50.94:8008
  PIPELINE_NAME: pipeline1
  DATA_SOURCE_FILE: data_source_3.json
  DATA_LOGIC_FILE: data_logic_3.json
  DATA_TARGET_FILE: data_target_3.json
  DATA_VARIABLES_FILE: data_vars_3.json
